# Generated by Django 6.0 on 2026-01-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
